#!/usr/bin/env python

from twisted.internet import protocol, reactor, endpoints

#Messages for the clients
c_message = {} 
#Messages for the master
m_message = []
#List of ip connected
ip_list = []
#Number of connected clients
cnt_clients = 0 #Number of connected clients

class echoClient(protocol.Protocol):
    def __init__(self, factory):
        self.factory = factory

    def connectionMade(self):
        global cnt_clients
        global c_message
        global ip_list
        self.peer_host = self.transport.getPeer().host
        self.peer_port = self.transport.getPeer().port
        self.factory.clients[self.peer_host] = self
        ip_list.append(self.peer_host)
        print('[*]Client %s:%s connected' %(self.peer_host, self.peer_port))
	print('[DEBUG] @param ip_list = %s' %(str(ip_list)))
        cnt_clients += 1
        print('[%s]Clients status' %(cnt_clients))
        self.sendMessage(c_message)

    def connectionLost(self, reason):
        global cnt_clients
        cnt_clients -= 1
        self.factory.clients.pop(self.peer_host, None)
	ip_list.remove(self.peer_host)
        print('[*] Client %s:%s disconnected' %(self.peer_host, self.peer_port))
        print('[%s] Client status ' %(cnt_clients))
	
    #TODO Message updating (IMPORTANT)
    def sendMessage(self, msg):
        if msg:
            print('message %s' %(msg))
            for m_key, m_value in msg.items():
                for c_key, c_value in self.factory.clients.items():
                    if m_key == c_key:
                        rm_key = m_key
                        self.factory.clients[c_key].transport.write(m_value.encode('utf-8'))
            msg.pop(rm_key, None)
        else:
            pass

    def dataReceived(self, data):
	print("a")
        
    def generateResponse():
	print("b")

class clientFactory(protocol.Factory):
    def __init__(self):
        self.clients = {}

    def buildProtocol(self, addr):
        print(addr)
        return echoClient(self)

class echoMaster(protocol.Protocol):
    def connectionMade(self):
        global ip_list
        self.master_host = self.transport.getPeer().host
        print('*- Master [%s] connected -*' %(self.master_host))
        send_ip = ":".join(ip_list)
        self.transport.write(send_ip.encode('utf-8'))

    def dataReceived(self, data):
        self.parseData(data)

    def connectionLost(self, reason):
        print('*- Master [%s] disconnected -*' %(self.master_host))

    def parseData(self, data):
        print(data)
        global message
        data = data.decode('utf-8')
        p_data = data.split('*')
        peer_ip = p_data[0]
        peer_msg = p_data[1]
        msg = message[peer_ip] = peer_msg

class masterFactory(protocol.Factory):
    def buildProtocol(self, addr):
        return echoMaster()

def main():
    endpoints.serverFromString(reactor, "tcp:8081:interface=127.0.0.1").listen(clientFactory())
    endpoints.serverFromString(reactor, "tcp:8080:interface=127.0.0.1").listen(masterFactory())
    reactor.run()

if __name__ == '__main__':
    main()
